### ISSUE TITLE
driving-traffic

### ISSUE THREAD

**Issue by davidsavoya** [mapbox/mapbox-sdk-rb#15]
Is the driving-traffic just available in the v5 app? I was able to change directions.rb to go to the desired endpoint but would rather stay on your gem. Is there something we are missing? I can make a pull request to point directions to v5 if you want.

**Comment by davidsavoya** [comment]
Although the geometry response looks much different so that may not be wanted.

**Comment by samfader** [comment]
This is now available: https://github.com/mapbox/mapbox-sdk-rb/pull/20
