### ISSUE TITLE
API Request Using Proxy

### ISSUE THREAD

**Issue by charliegeiger89** [mapbox/mapbox-sdk-rb#18]
Is there currently any way to specify a proxy when making API requests? I am trying to avoid setting a global proxy value via `RestClient.proxy = ENV['http_proxy']`.

I was attempting something like this:
`Mapbox::Geocoder.geocode_forward("foo", limit: 1, proxy: "http://1.2.3.4:8080")`

**Comment by KaiBot3000** [comment]
@charliegeiger89 can you say more about your need for this feature? Proxying requests to Mapbox APIs for the purpose of redistribution is against [Mapbox TOS](https://www.mapbox.com/tos/#[YmcMYmns])
