### ISSUE TITLE
rest-client v2.0 compatibility?

### ISSUE THREAD

**Issue by benoitongit** [mapbox/mapbox-sdk-rb#25]
Hi,
Any plan to update to rest-client v2.0+?
The current version is quite outdated.

Thanks,
Benoit

**Comment by samfader** [comment]
This is now updated: https://github.com/mapbox/mapbox-sdk-rb/pull/26

**Comment by jonathankau** [comment]
@samfader Any chance you could bump the gem version on Rubygems so that we don't have to switch our Gemfiles to point to the Github repo? Thanks!

**Comment by samfader** [comment]
Done, @jonathankau! Thanks for pointing that out.
