### ISSUE TITLE
Undefined method 'round' for nil:NilClass when running reverse geocoder example

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-sdk-rb#27]
When I try to run the reverse geocoding example from the README:

```
placenames = Mapbox::Geocoder.geocode_reverse({
  "latitude" => 38,
  "longitude" => -100
})
```

I get the following error:

```
Traceback (most recent call last):
        3: from /usr/local/opt/ruby/bin/irb:11:in `<main>'
        2: from (irb):3
        1: from /Users/samfader/mapbox/mapbox-sdk-rb/lib/mapbox/geocoder.rb:47:in `geocode_reverse'
NoMethodError (undefined method `round' for nil:NilClass)
```

**Comment by aehven** [comment]
I find this works better with ':' instead of '=>' notation.  So 
````
Mapbox::Geocoder.geocode_reverse({"latitude" => 38, "longitude" => -100})
````
fails but
````
Mapbox::Geocoder.geocode_reverse({latitude: 38, longitude: -100})
````
succeeds whether you use symbols or strings for the attribute names.

> When I try to run the reverse geocoding example from the README:
> 
> ```
> placenames = Mapbox::Geocoder.geocode_reverse({
>   "latitude" => 38,
>   "longitude" => -100
> })
> ```
> I get the following error:
> 
> ```
> Traceback (most recent call last):
>         3: from /usr/local/opt/ruby/bin/irb:11:in `<main>'
>         2: from (irb):3
>         1: from /Users/samfader/mapbox/mapbox-sdk-rb/lib/mapbox/geocoder.rb:47:in `geocode_reverse'
> NoMethodError (undefined method `round' for nil:NilClass)
> ```

**Comment by samfader** [comment]
Nice find, @aehven. I can look into this a bit more later.

**Comment by samfader** [comment]
Updated the README, should be good for now.

**Comment by aehven** [comment]
> Updated the README, should be good for now.

Cool.  Thanks!
