### ISSUE TITLE
Bump version and publish

### ISSUE THREAD

**Issue by choix** [mapbox/mapbox-sdk-rb#36]
I have noticed that there is a discrepancy in code between current master and version on rubygems.
As you can seen on https://rubygems.org/gems/mapbox-sdk last release was made in August 16, 2018.

The problem is that current documentation does not match version published on rubygems. For example in published version `Mapbox::Direction.directions` expects only 2 params, while documentation gives an example of 3 params. As I see changes were done in October with https://github.com/mapbox/mapbox-sdk-rb/pull/28 but were never published to rubygems.

Could you please bump it to v2.2 and publish it?

**Comment by samfader** [comment]
Good catch, thanks @choix. 

https://rubygems.org/gems/mapbox-sdk/versions/2.2.0
