### ISSUE TITLE
Bumping rest-client from 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by andrii-rymar** [mapbox/mapbox-sdk-rb#50]
Hi,
rest-client 2.0.1 used in the project is now almost 4 year behind and causes compatibility issues.
Do you have any plans to update it to 2.1.0?
Thanks

**Comment by samfader** [comment]
@andrii-rymar This library doesn't have a maintainer anymore - it's owned by the community at this point. If you are open to updating the library to support rest-client 2.1.0 I'd be happy to review a PR.
