### ISSUE TITLE
Bump version and publish to rubygems

### ISSUE THREAD

**Issue by mattficke** [mapbox/mapbox-sdk-rb#9]
@tmcw, do you have the keys to publish to rubygems? The bbox changes have been merged into master.

**Comment by tmcw** [comment]
Yep, what's your email address on rubygems.org?

**Comment by mattficke** [comment]
@tmcw email is matt@mattficke.com, username is mattficke.

**Comment by tmcw** [comment]
👍 done

**Comment by mattficke** [comment]
Great. Bumping to 2.0.0 since the options param is a breaking change for anyone who was using the old proximity param.
